#ifndef NU_BUILD_CONFIG_H
#define NU_BUILD_CONFIG_H

#ifdef NU_WITH_EVERYTHING
#	define NU_WITH_UTF8
#	define NU_WITH_CESU8
#	define NU_WITH_STRINGS
#endif /* NU_WITH_EVERYTHING */

#ifdef NU_WITH_UTF8
#	define NU_WITH_UTF8_READER
#	define NU_WITH_UTF8_WRITER
#endif /* NU_WITH_UTF8 */

#ifdef NU_WITH_CESU8
#	define NU_WITH_CESU8_READER
#	define NU_WITH_CESU8_WRITER
#endif /* NU_WITH_CESU8 */

#ifdef NU_WITH_STRINGS
#	define NU_WITH_ZERO_STRINGS
#	define NU_WITH_N_STRINGS
#endif /* NU_WITH_STRINGS */

#endif /* NU_BUILD_CONFIG_H */
