#!/usr/bin/python

import sys
from unidata import *


def pass_mapping(mapping):
	allowed = ('',
		'<noBreak>',
		'<wide>',     # full width characters
		'<narrow>',   # half width characters
		'<small>',    # CNS compat
		'<initial>',
		'<medial>',
		'<final>',
		'<isolated>',
	)

	return mapping.strip() in allowed

d = dict()

for line in sys.stdin:
	if unidata_comment(line):
		continue

	tokens = line.split(';')
	codepoint, mapping, replacement = tokens[0:3]

	if not pass_mapping(mapping):
		continue

	d[unidata_strip(codepoint)] = unidata_split(replacement)

for codepoint, replacement in sorted(d.iteritems()):
	print '%06X %s' % (int(codepoint, base=16), ','.join(replacement))
