#!/usr/bin/python

import sys

from mph import *

def usage():
	print 'usage: %s <TAG>' % sys.argv[0]

if len(sys.argv) < 2:
	usage()
	sys.exit(1)

TAG = sys.argv[1]

dict = {}

for i, line in enumerate(sys.stdin):
	codepoint, replacement = filter(bool, line.strip().split(' '))

	if not replacement:
		continue

	replacement = int(replacement.strip(), base=16)
	dict[codepoint] = (codepoint, replacement)

(G, V) = CreateMinimalPerfectHash(dict)

assert(len(G) == len(V))

GenerateInfo(TAG, G, [])
GenerateIncludes()
GenerateG(TAG, G)
GenerateValues(TAG, G, V)
