#!/usr/bin/python

import sys
from unidata import *

d = dict()

for line in sys.stdin:
	if unidata_comment(line):
		continue

	tokens = line.split(';')
	codepoint, lower = tokens[0], tokens[13]

	if not lower:
		continue

	d[unidata_strip(codepoint)] = unidata_split(lower)

for codepoint, replacement in sorted(d.iteritems()):
	print '%06X %s' % (int(codepoint, base=16), ','.join(replacement))
