#!/usr/bin/python

import sys

def pass_code(codepoint, category, decomps):
	return category in ('Ll', 'Lu', 'Lt', 'Nl', 'Nd') \
	and decomps.find('<') < 0

for line in sys.stdin:
	codepoint, _, category, _, decomps = line.strip().split(';')[0:5]
	if pass_code(codepoint, category, decomps):
		print codepoint
		
