set(NDK_ROOT "/opt/arm-linux-androideabi-4.8" CACHE PATH "Android NDK root dir" FORCE)

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_C_COMPILER ${NDK_ROOT}/bin/arm-linux-androideabi-gcc)
set(CMAKE_FIND_ROOT_PATH ${NDK_ROOT})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
