set(NDK_ROOT "/opt/mipsel-linux-android-4.8" CACHE PATH "Android NDK root dir" FORCE)

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_C_COMPILER ${NDK_ROOT}/bin/mipsel-linux-android-gcc)
set(CMAKE_FIND_ROOT_PATH ${NDK_ROOT})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
