1. Build libnu.a
2. gcc -I.. -DNU_WITH_EVERYTHING -DNU_DYNAMIC_EXTENSION -fPIC -shared -O3 nu.c libnu.a -o libnusqlite3.so

Or

3. gcc -I.. -DNU_WITH_EVERYTHING -c -O3 nu.c -o nu.o

And link statically.
